### ISSUE TITLE
[RFE] include the github user in twitter output

### ISSUE THREAD

**Issue by juhp** [benbjohnson/grapevine#1]
Thanks for making grapevine. :)

I would like to suggest changing the format of the tweeter output to mention also the github username.

eg Here is the current format from a recent @github_hs tweet:

<<<
sstg - Simplified, Serializable STG http://bit.ly/ekEDhl

How about not using bit.ly (it is hiding useful information)
and showing the above post like this instead:

<<<
https://github.com/gergoerdi/sstg - Simplified, Serializable STG

Yes, it is a few characters longer (in this case the user has 9 chars)
but now it is clear who's repo has been updated.

How do you think?  I feel this change would make your github grapevines more readable and informative.

**Comment by benbjohnson** [comment]
That's a good idea to put the full URL at the beginning of the tweet. I didn't think about consolidating the URL and project name together.  However, it poses a few problems:
1. The description already gets truncated pretty often. Every character counts.
2. I'd like to make the bit.ly click info publicly available eventually. You can actually see the click info for a bit.ly URL by adding a `+` to the end of the url like this: http://bit.ly/ekEDhl+   You can also see a full timeline of Grapevine URL stats here: http://bit.ly/u/benbjohnson
3. Twitter automatically shortens some URLs to use their `t.co` domain. This would eliminate the username and project name.

I've thought about spidering for user's twitter names from the URL specified in their GitHub account page and displaying that. I think it would be good to let people know that their projects are being talked about. It would take up more characters in the tweet though. Although some people may find it annoying to get mentioned.

Ben

**Comment by juhp** [comment]
Ok, well how about writing:
"""
gergoerdi/sstg - Simplified, Serializable STG http://bit.ly/ekEDhl
"""
then?

**Comment by benbjohnson** [comment]
I can add that. I don't have time right now though. Feel free to do a pull request if you want to make the change.
